# Generated by Django 4.1.3 on 2022-11-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agnam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agnam',
            name='Poster',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
