# Generated by Django 4.1.3 on 2022-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agnam', '0003_alter_agnam_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agnam',
            name='Poster',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
