# Generated by Django 4.1.3 on 2022-12-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agnam', '0006_alter_agnam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agnam',
            name='Poster',
            field=models.CharField(max_length=1000),
        ),
    ]
