# Generated by Django 4.1.3 on 2023-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agnam', '0007_alter_agnam_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agnam',
            name='URL',
            field=models.URLField(max_length=1000),
        ),
    ]
