# Generated by Django 4.2.1 on 2023-05-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agnam', '0008_alter_agnam_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('URL', models.URLField(max_length=1000)),
                ('Poster', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Agnam',
        ),
    ]
