# Generated by Django 4.2.1 on 2023-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agnam', '0009_comic_delete_agnam'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
